// Code generated by goagen v1.4.0, DO NOT EDIT.
//
// unnamed API: Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/aya-eiya/goa-test/design/app
// --out=$(GOPATH)/src/github.com/aya-eiya/goa-test/apps
// --version=v1.4.0

package app
